//
//  AuthorizationStoryPresenter.swift
//  tUP
//
//  Created by Home on 07.03.2020.
//  Copyright (c) 2020 Home. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AuthorizationStoryPresentationLogic {
    func presentLoadedContent(response: AuthorizationStory.Photo.Response)
}

class AuthorizationStoryPresenter: AuthorizationStoryPresentationLogic {

    weak var viewController: AuthorizationStoryDisplayLogic?
  
    func presentLoadedContent(response: AuthorizationStory.Photo.Response) {
        
        let viewModel = AuthorizationStory.Photo.ViewModel(photo: response.photo)
        viewController?.displayLoadedContent(request: viewModel)
    }
}
