//
//  AuthorizationStoryPresenter.swift
//  tUP
//
//  Created by Home on 07.03.2020.
//  Copyright (c) 2020 Home. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AuthorizationStoryPresentationLogic {
    func presentRandomPhoto(response: AuthorizationStory.Photo.Response)
}

class AuthorizationStoryPresenter: AuthorizationStoryPresentationLogic {
  
  weak var viewController: AuthorizationStoryDisplayLogic?
  
    func presentRandomPhoto(response: AuthorizationStory.Photo.Response) {
          
        if let photo = response.photo, let url = URL(string: photo.source.portrait) {
            let viewModel = AuthorizationStory.Photo.ViewModel(photoUrl: url, error: nil)
            viewController?.displayPhoto(viewModel: viewModel)
        }

        if let error = response.error {
            let viewModel = AuthorizationStory.Photo.ViewModel(photoUrl: nil, error: error)
            viewController?.displayError(viewModel: viewModel)
        }
    }
}
