//
//  AuthorizationStoryInteractor.swift
//  tUP
//
//  Created by Home on 07.03.2020.
//  Copyright (c) 2020 Home. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AuthorizationStoryBusinessLogic {
//    func getRandomPhoto(request: AuthorizationStory.Photo.Request)
    func loadContent(request: AuthorizationStory.Photo.Request)
}

protocol AuthorizationStoryDataStore {
    var image: UIImage? { get set }
}

class AuthorizationStoryInteractor: AuthorizationStoryBusinessLogic, AuthorizationStoryDataStore {
  
    var presenter: AuthorizationStoryPresentationLogic?
    var worker = AuthorizationStoryWorker()

    var image: UIImage?
    
    func loadContent(request: AuthorizationStory.Photo.Request) {
        
        guard let image = image else { return }
        
        let response = AuthorizationStory.Photo.Response(photo: image)

        presenter?.presentLoadedContent(response: response)
        
    }
}
