//
//  AuthorizationStoryWorker.swift
//  tUP
//
//  Created by Home on 07.03.2020.
//  Copyright (c) 2020 Home. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class AuthorizationStoryWorker {
  
    public func getRandomPhoto(completionBlock: @escaping ( _ photo: PhotoModel?,  _ error: Error?) -> ()) {
        
        NetworkManager.shared.getRandomPhoto(completionBlock: completionBlock)
    }
}
