//
//  AuthorizationStoryModels.swift
//  tUP
//
//  Created by Home on 07.03.2020.
//  Copyright (c) 2020 Home. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AuthorizationStory
{
  // MARK: Use cases
  
    enum Photo {
        struct Request {}
        struct Response {
            
            let photo: PhotoModel?
            let error: Error?
        }
        
        struct ViewModel {
            
            let photoUrl: URL?
            let error: Error?
        }
    }
}
