//
//  ImitationLaunchScreenWorker.swift
//  tUP
//
//  Created by Home on 07.03.2020.
//  Copyright (c) 2020 Home. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Nuke

class ImitationLaunchScreenWorker {
    
    public func getRandomPhoto(completionBlock: @escaping ( _ photo: PhotoModel?,  _ error: Error?) -> ()) {
        NetworkManager.shared.getRandomPhoto(completionBlock: completionBlock)
    }
    
    public func getPhotoBy(url: URL, completionBlock: @escaping ( _ photo: UIImage?,  _ error: Error?) -> ()) {
        ImagePipeline.shared.loadImage(with: url) { response, error in
            completionBlock(response?.image, error)
        }
    }
}
