//
//  ImitationLaunchScreenModels.swift
//  tUP
//
//  Created by Home on 07.03.2020.
//  Copyright (c) 2020 Home. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ImitationLaunchScreen {
      
    enum PhotoInfo {
        struct Request {}
        struct Response {
            let photo: PhotoModel?
            let error: Error?
        }
        struct ViewModel {
            let photoUrl: URL?
            let error: Error?
        }
    }
    
    enum PhotoPreview {
        struct Request {
            let imageLink: URL
        }
        struct Response {
            let photo: UIImage?
            let error: Error?
        }
        struct ViewModel {
            let photo: UIImage?
            let error: Error?
        }
    }
    
    enum PhotoToSet {
        struct Request {
            let photo: UIImage
        }
        struct Response {}
        struct ViewModel {}
    }
}
