//
//  ImitationLaunchScreenViewController.swift
//  tUP
//
//  Created by Home on 07.03.2020.
//  Copyright (c) 2020 Home. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ImitationLaunchScreenDisplayLogic: class
{
  func displaySomething(viewModel: ImitationLaunchScreen.Something.ViewModel)
}

class ImitationLaunchScreenViewController: UIViewController, ImitationLaunchScreenDisplayLogic
{
  var interactor: ImitationLaunchScreenBusinessLogic?
  var router: (NSObjectProtocol & ImitationLaunchScreenRoutingLogic & ImitationLaunchScreenDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = ImitationLaunchScreenInteractor()
    let presenter = ImitationLaunchScreenPresenter()
    let router = ImitationLaunchScreenRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
    setupUI()
  }
    
    override func viewDidAppear(_ animated: Bool) {
            
         DispatchQueue.main.asyncAfter(deadline: .now() + 1) { [weak self] in
             self?.router?.navigateToAuthorizationStory()
         }
     }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = ImitationLaunchScreen.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: ImitationLaunchScreen.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}

private extension ImitationLaunchScreenViewController {
    
    func setupUI() {
        
        navigationController?.setNavigationBarHidden(true, animated: false)

    }
}

