//
//  ImitationLaunchScreenPresenter.swift
//  tUP
//
//  Created by Home on 07.03.2020.
//  Copyright (c) 2020 Home. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ImitationLaunchScreenPresentationLogic {
    func presentRandomPhotoInfo(response: ImitationLaunchScreen.PhotoInfo.Response)
    func presentPhoto(response: ImitationLaunchScreen.PhotoPreview.Response)
    
    func presentPhotoToSet(response: ImitationLaunchScreen.PhotoToSet.Response)
}

class ImitationLaunchScreenPresenter: ImitationLaunchScreenPresentationLogic {
 
    weak var viewController: ImitationLaunchScreenDisplayLogic?
  
    func presentRandomPhotoInfo(response: ImitationLaunchScreen.PhotoInfo.Response) {
          
        if let photo = response.photo, let url = URL(string: photo.source.portrait) {
            let viewModel = ImitationLaunchScreen.PhotoInfo.ViewModel(photoUrl: url, error: nil)
            viewController?.displayPhotoInfo(viewModel: viewModel)
        }

        if let error = response.error {
            let viewModel = ImitationLaunchScreen.PhotoInfo.ViewModel(photoUrl: nil, error: error)
            viewController?.displayErrorInfo(viewModel: viewModel)
        }
    }
    
    func presentPhoto(response: ImitationLaunchScreen.PhotoPreview.Response) {
        
        if let photo = response.photo {
            let viewModel = ImitationLaunchScreen.PhotoPreview.ViewModel(photo: photo, error: nil)
            viewController?.displayPhoto(viewModel: viewModel)
        }
        
        if let error = response.error {
            let viewModel = ImitationLaunchScreen.PhotoPreview.ViewModel(photo: nil, error: error)
            viewController?.displayPhotoError(viewModel: viewModel)
        }
    }
    
    func presentPhotoToSet(response: ImitationLaunchScreen.PhotoToSet.Response) {
        
        let viewModel = ImitationLaunchScreen.PhotoToSet.ViewModel()
        viewController?.displayPhotoToSet(viewModel: viewModel)
    }
}
