//
//  ImitationLaunchScreenRouter.swift
//  tUP
//
//  Created by Home on 07.03.2020.
//  Copyright (c) 2020 Home. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ImitationLaunchScreenRoutingLogic
{
    func navigateToAuthorizationStory()
}

protocol ImitationLaunchScreenDataPassing
{
  var dataStore: ImitationLaunchScreenDataStore? { get }
}

class ImitationLaunchScreenRouter: NSObject, ImitationLaunchScreenRoutingLogic, ImitationLaunchScreenDataPassing
{
  weak var viewController: ImitationLaunchScreenViewController?
  var dataStore: ImitationLaunchScreenDataStore?
  
    // MARK: Routing
    func navigateToAuthorizationStory() {
        
        viewController?.performSegue(withIdentifier: R.segue.imitationLaunchScreenViewViewController.authorizationStory.identifier, sender: .none)
        
    }
}
