//
//  ImitationLaunchScreenInteractor.swift
//  tUP
//
//  Created by Home on 07.03.2020.
//  Copyright (c) 2020 Home. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ImitationLaunchScreenBusinessLogic
{
  func doSomething(request: ImitationLaunchScreen.Something.Request)
}

protocol ImitationLaunchScreenDataStore
{
  //var name: String { get set }
}

class ImitationLaunchScreenInteractor: ImitationLaunchScreenBusinessLogic, ImitationLaunchScreenDataStore
{
  var presenter: ImitationLaunchScreenPresentationLogic?
  var worker: ImitationLaunchScreenWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ImitationLaunchScreen.Something.Request)
  {
    worker = ImitationLaunchScreenWorker()
    worker?.doSomeWork()
    
    let response = ImitationLaunchScreen.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
