//
//  ImitationLaunchScreenPresenter.swift
//  tUP
//
//  Created by Home on 07.03.2020.
//  Copyright (c) 2020 Home. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ImitationLaunchScreenPresentationLogic
{
  func presentSomething(response: ImitationLaunchScreen.Something.Response)
}

class ImitationLaunchScreenPresenter: ImitationLaunchScreenPresentationLogic
{
  weak var viewController: ImitationLaunchScreenDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ImitationLaunchScreen.Something.Response)
  {
    let viewModel = ImitationLaunchScreen.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
