//
//  ImitationLaunchScreenRouter.swift
//  tUP
//
//  Created by Home on 07.03.2020.
//  Copyright (c) 2020 Home. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ImitationLaunchScreenRoutingLogic {
    func routeToAuthorizationStory(segue: UIStoryboardSegue)
    func navigateToHome()
}

protocol ImitationLaunchScreenDataPassing {
  var dataStore: ImitationLaunchScreenDataStore? { get }
}

class ImitationLaunchScreenRouter: NSObject, ImitationLaunchScreenRoutingLogic, ImitationLaunchScreenDataPassing {

    weak var viewController: ImitationLaunchScreenViewController?
    var dataStore: ImitationLaunchScreenDataStore?
  
    // MARK: Routing
    
    func routeToAuthorizationStory(segue: UIStoryboardSegue) {
    
        let authorizationViewController = segue.destination as? AuthorizationStoryViewController
        var authorizationDataStore = authorizationViewController?.router?.dataStore
        authorizationDataStore?.image = dataStore?.image
    }
    
    func navigateToHome() {
        
        viewController?.performSegue(withIdentifier: R.segue.imitationLaunchScreenViewController.home.identifier, sender: .none)
        
    }
}
